sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CIJJ9HPDWtXcj8x5XjrrkSCoETiEkW1hDea/cnrXYl7UG1QrIUfTjidUT+sQ6T+uQ5q+wYRIm/OBLbfPdaPo8yWH2c510BdfGvBxZrNrlr1TQWAoI4Mt0gUen6yAkLN8swcyc806RL24DJ4zmH+8Kk4iyk/RCvCR7EN3F5ORtPnOHOoz0XReU+SE5QT+a+Y/N3PgTsBDw37fLb9Z+R98sLgfkfxL66mDsMns0s2zXi/0a4E9i2QzCmWjazrbYPv476hZSXzRmFOLLa63cm9YMwtOZAoCBQzoUuqgP1EU1AQFy6PpDXo2vz7G1GI9kUmm7t1jGVgjRlqqmB4Htkg0HR9PBKPx6/+01HzW1TjurAaG7/jPkKLPjCqPRbo4ozyAinkSqitsnpt4E04Xomf9biEKQ52syQZ1HNQXFelynuNNxjT+tLjjH4F++OLc9ydAzbq7fQdp5ICNRABnDYnPfPcDT0rLq9U7kuiivADKErhqNQzKFQp53jaEdVdWzePWfS8Y43Z7VR/bExhSDhitsnumX1w9xs+sVeEG98EotObN3EOEtowGoLaezBF2+JwlkLg7b2vAq0q6f4PS2ACkYX0I7zx2jlDMA/6DQUBXVCP0Jy5ta5bHb3zOxPXyIyCD0wciqobfvzz9d3NLM+ujyv55Zlg5WubB8m789K9qXjs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Monsieur-de-Camors-Volume-2_3944
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy